// ==UserScript==
// @name         Youtube Music Tweak
// @description  -
// @icon         https://www.google.com/s2/favicons?sz=64&domain=music.youtube.com
// @author       dannycreations
// @version      0.0.4
// @namespace    https://github.com/dannycreations/Peke
// @homepage     https://github.com/dannycreations/Peke
// @match        *://music.youtube.com/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

var PekeMonorepo=function(e){function t(e,t,{signal:n,edges:r}={}){let l,o=null;const s=null!=r&&r.includes("leading"),c=null==r||r.includes("trailing"),i=()=>{null!==o&&(e.apply(l,o),l=void 0,o=null)};let u=null;const a=()=>{null!=u&&clearTimeout(u),u=setTimeout(()=>{u=null,c&&i(),d()},t)},d=()=>{null!==u&&(clearTimeout(u),u=null),l=void 0,o=null},f=function(...e){if(n?.aborted)return;l=this,o=e;const t=null==u;a(),s&&t&&i()};return f.schedule=a,f.cancel=d,f.flush=()=>{i()},n?.addEventListener("abort",d,{once:!0}),f}Object.defineProperty(e,Symbol.toStringTag,{value:"Module"});var n=0,r=null,l=null,o={K:1e3,M:1e6,B:1e9};function s(e){if(!e)return 0;const t=e.trim().toUpperCase().match(/^([\d.,]+)\s*([KMB])?\b/);if(!t)return 0;const n=parseFloat(t[1].replace(/,/g,""));if(Number.isNaN(n))return 0;const r=t[2];return r&&r in o?n*o[r]:n}function c(e){const t=e.querySelectorAll("ytmusic-responsive-list-item-renderer"),n=t.length;let r=null,l=null;if(n>0){const e=t[0].querySelector("a[href]");e?.href&&(r=e.href);const o=t[n-1].querySelector("a[href]");o?.href&&(l=o.href)}return{length:n,firstElement:r,lastElement:l}}function i(){const e=document.querySelector("ytmusic-playlist-shelf-renderer #contents");if(!e)return;const t=e.querySelector("ytmusic-continuation-item-renderer"),o=e.querySelectorAll("ytmusic-responsive-list-item-renderer");if(o.length<2)return;const i=[];let u=!0;for(let n=0;n<o.length;n++){const e=o[n],t=e.querySelector('yt-formatted-string[title*=" plays"]'),r=t?s(t.title):0;i.push({element:e,plays:r}),u&&n>0&&i[n-1].plays<r&&(u=!1)}const a=c(e);if(n=a.length,r=a.firstElement,l=a.lastElement,u)return;i.sort((e,t)=>t.plays-e.plays);const d=document.createDocumentFragment();for(const{element:n}of i)d.appendChild(n);t&&d.appendChild(t),e.replaceChildren(d)}return function(e,t={}){"complete"===document.readyState?e():window.addEventListener("load",e,t)}(function(){i();const e=t(i,100);!function(e,t={}){const{target:n=document.body,options:r={}}=t,l=new MutationObserver((t,n)=>{try{e(t)}catch(r){throw n.disconnect(),r}});l.observe(n,{childList:!0,subtree:!0,...r})}(t=>{let o=!1;const s=t.length;for(let e=0;e<s;e++){const n=t[e],r=n.addedNodes.length;if(r>0)for(let e=0;e<r;e++){const t=n.addedNodes[e];if(t instanceof HTMLElement&&(t.matches("ytmusic-responsive-list-item-renderer")||null!==t.querySelector("ytmusic-responsive-list-item-renderer"))){o=!0;break}}if(o)break}if(!o)return;const i=document.querySelector("ytmusic-playlist-shelf-renderer #contents");if(!i)return;const u=c(i),a=u.length!==n,d=u.lastElement!==l,f=u.firstElement!==r;(a||d||f)&&e()},{target:document.querySelector("ytmusic-app-layout")||document.body})}),e.parsePlayCount=s,e}({});